"""Initial migration with users, monitors, and ssl_checks tables

Revision ID: 370a9c7b5096
Revises: 
Create Date: 2025-11-12 21:37:19.136086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a9c7b5096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssl_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ssl_status', sa.String(), nullable=True),
    sa.Column('server_status', sa.String(), nullable=True),
    sa.Column('ip_status', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_checks_domain'), 'ssl_checks', ['domain'], unique=False)
    op.create_index(op.f('ix_ssl_checks_id'), 'ssl_checks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_domain'), 'monitors', ['domain'], unique=False)
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_domain'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ssl_checks_id'), table_name='ssl_checks')
    op.drop_index(op.f('ix_ssl_checks_domain'), table_name='ssl_checks')
    op.drop_table('ssl_checks')
    # ### end Alembic commands ###
