"""Add alert_configs table for user-managed alerts

Revision ID: 5f26bc034a6d
Revises: a5ad82218b13
Create Date: 2025-11-14 01:14:33.545453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f26bc034a6d'
down_revision: Union[str, None] = 'a5ad82218b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('alert_30_days', sa.Boolean(), nullable=True),
    sa.Column('alert_7_days', sa.Boolean(), nullable=True),
    sa.Column('alert_1_day', sa.Boolean(), nullable=True),
    sa.Column('alert_ssl_errors', sa.Boolean(), nullable=True),
    sa.Column('alert_geo_changes', sa.Boolean(), nullable=True),
    sa.Column('alert_cert_expired', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_configs_id'), 'alert_configs', ['id'], unique=False)
    op.create_index(op.f('ix_alert_configs_organization_id'), 'alert_configs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alert_configs_user_id'), 'alert_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_configs_user_id'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_organization_id'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_id'), table_name='alert_configs')
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
