"""Add organizations and alerts tables with multi-user isolation

Revision ID: a5ad82218b13
Revises: e4b85a247cd7
Create Date: 2025-11-13 15:06:06.763092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ad82218b13'
down_revision: Union[str, None] = 'e4b85a247cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create organizations table
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    
    # Create alerts table
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_domain'), 'alerts', ['domain'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    
    # Update existing tables using batch mode for SQLite compatibility
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_monitors_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitors_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_monitors_organization', 'organizations', ['organization_id'], ['id'])
    
    with op.batch_alter_table('ssl_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ssl_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_checks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_checks_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_ssl_checks_organization', 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_ssl_checks_user', 'users', ['user_id'], ['id'])
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_organization', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_organization', type_='foreignkey')
        batch_op.drop_column('organization_id')
    
    with op.batch_alter_table('ssl_checks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ssl_checks_user', type_='foreignkey')
        batch_op.drop_constraint('fk_ssl_checks_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ssl_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_ssl_checks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ssl_checks_checked_at'))
        batch_op.drop_column('organization_id')
        batch_op.drop_column('user_id')
    
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_monitors_organization', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_monitors_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitors_organization_id'))
        batch_op.drop_column('organization_id')
    
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_domain'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
