"""Update user model for JWT authentication

Revision ID: e4b85a247cd7
Revises: 370a9c7b5096
Create Date: 2025-11-13 01:32:33.813255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b85a247cd7'
down_revision: Union[str, None] = '370a9c7b5096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to handle schema changes properly
    # This migration drops and recreates the users table
    
    # Create a new users table with updated schema
    op.execute("""
        CREATE TABLE users_new (
            id INTEGER PRIMARY KEY,
            email VARCHAR NOT NULL UNIQUE,
            hashed_password VARCHAR NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT 1,
            is_superuser BOOLEAN NOT NULL DEFAULT 0,
            is_verified BOOLEAN NOT NULL DEFAULT 0,
            created_at DATETIME
        )
    """)
    
    # Copy data from old table to new table (if any exists)
    # Note: This will fail if there's existing data as we can't map username to email
    # In production, this would need a data migration script
    
    # Drop the old table
    op.execute("DROP TABLE users")
    
    # Rename the new table
    op.execute("ALTER TABLE users_new RENAME TO users")
    
    # Create indexes
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate old users table structure
    op.execute("""
        CREATE TABLE users_old (
            id INTEGER PRIMARY KEY,
            username VARCHAR NOT NULL UNIQUE,
            password_hash VARCHAR NOT NULL,
            role VARCHAR NOT NULL DEFAULT 'user',
            created_at DATETIME
        )
    """)
    
    op.execute("DROP TABLE users")
    op.execute("ALTER TABLE users_old RENAME TO users")
    
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
