[variables]
# NIXPACKS_NODE_VERSION = '22'
NODE_ENV = 'production'

[start]
  providers = ['node']
  cmd = './entrypoint.sh'

[phases.setup]
nixPkgs = ['caddy', 'nodejs-slim']

[phases.install]

[phases.build]
cmd = ['chmod +x ./entrypoint.sh']