[variables]
NIXPACKS_NODE_VERSION = '22'
NODE_ENV = 'production'

[start]
  runImage = 'debian:bullseye-slim'
  providers = ["node"]

[phases.setup]
nixPkgs = ['caddy']
aptPkgs = ['caddy']

[phases.install]
build.cmd = "npm install npm@latest -g"

[phases.start]
cmd = ["chmod +x ./entrypoint.sh"]

