[variables]
NIXPACKS_NODE_VERSION = '22'
NODE_ENV = 'production'

[start]
  providers = ['node']
  cmd = './entrypoint.sh'

[phases.setup]
nixPkgs = ['caddy']

[phases.install]
build.cmd = 'npm install npm@latest -g'

[phases.build]
cmd = ['chmod +x ./entrypoint.sh']