name: Build and push docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GB_TOKEN }}

      - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          context: ./n8n
          labels: |
            maintainer=tintn@vinahost.vn
            service=n8n_caddy
            env=production
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:build_at-${{ env.DATE_STAMP }}
            ${{ env.IMAGE_NAME }}:latest
